DEBUG = True

USERNAME = "root"
PASSWORD = "Everton12"
SERVER = "localhost"
DB = "mercado"

SQLALCHEMY_DATABASE_URI = f'mysql://{USERNAME}:{PASSWORD}@{SERVER}/{DB}'
SQLALCHEMY_TRACK_MODIFICATIONS = True

